image: java:8

stages:
  - test

before_script:
  - echo $BUILD_VERSION
  - apt-get update -y
  - apt-get install apt-transport-https -y
  - echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
  - curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add
  - apt-get update -y
  - apt-get install sbt -y
  - sbt sbtVersion

build_neutron:
  stage: test
  only:
    refs:
      - master
      - merge_requests
  script:
    - sbt -mem 2048 test
