image: hseeberger/scala-sbt:8u222_1.3.10_2.13.1

stages:
 - test

cache:
  paths:
    - "sbt-cache/ivy/cache"
    - "sbt-cache/boot"
    - "sbt-cache/sbtboot"
    - "sbt-cache/coursier"

build_neutron:
  stage: test
  only:
    refs:
      - master
      - merge_requests
  script:
    - sbt -mem 2048 test
