image: docker-registry:5000/sbt-docker:latest

variables:

SBT_OPTS: "-Dsbt.global.base=sbt-cache/sbtboot -Dsbt.boot.directory=sbt-cache/boot -Dsbt.ivy.home=sbt-cache/ivy Dsbt.coursier.home=sbt-cache/coursier -Dsbt.io.jdktimestamps=true"

COURSIER_CACHE: sbt-cache/coursier

stages:
 - test

cache:
  paths:
    - "sbt-cache/ivy/cache"
    - "sbt-cache/boot"
    - "sbt-cache/sbtboot"
    - "sbt-cache/coursier"

build_neutron:
  stage: test
  only:
    refs:
      - master
      - merge_requests
  script:
    - sbt -mem 2048 test
