image: hseeberger/scala-sbt:8u222_1.3.5_2.13.1

stages:
 - test

cache:
  paths:
    - "$HOME/.ivy/cache"
    - "$HOME/.cache/coursier"
    - "$HOME/.sbt/boot"

build_neutron:
  stage: test
  only:
    refs:
      - master
      - merge_requests
  script:
    - sbt -mem 2048 test
