image: nightscape/scala-mill

variables:
  COURSIER_CACHE: $CI_PROJECT_DIR/.cache/coursier

cache: &global_cache
  key: $CI_BUILD_REF_NAME
  untracked: false

stages:
  - test

build_neutron:
  stage: build
  cache:
    <<: *global_cache
    key: core
    paths:
      - $CI_PROJECT_DIR/.cache
      - $CI_PROJECT_DIR/out/core
  only:
    refs:
      - master
      - merge_requests
    changes:
      - /**/*.scala
      - /**/*.sc
  script:
    - mill -i core.test
