image: 035187777769.dkr.ecr.us-east-1.amazonaws.com/build-runner:dd0fb6cc

variables:
  COURSIER_CACHE: $CI_PROJECT_DIR/.cache/coursier

cache: &global_cache
  key: $CI_BUILD_REF_NAME
  untracked: false

stages:
  - build

build_neutron:
  stage: build
  cache:
    <<: *global_cache
    key: core
    paths:
      - $CI_PROJECT_DIR/.cache
      - $CI_PROJECT_DIR/out/core
  image:
    name: $ECR_URL/builder-kaniko-mill:latest
    entrypoint: [""]
  only:
    refs:
      - master
      - merge_requests
    changes:
      - **/*
  script:
    - ./mill -i -h . core.compile
