addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.11.2")
addSbtPlugin("com.github.sbt" % "sbt-header"     % "5.11.0")
addSbtPlugin("io.spray"       % "sbt-revolver"   % "0.10.0")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"   % "2.5.2")
addSbtPlugin("org.typelevel"  % "sbt-tpolecat"   % "0.5.2")
