addSbtPlugin("com.geirsson"              % "sbt-ci-release" % "1.5.3")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"     % "5.6.0")
addSbtPlugin("io.spray"                  % "sbt-revolver"   % "0.9.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"   % "2.4.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"   % "0.1.13")
